// Code generated by goctl-resty-discover. DO NOT EDIT.
package client
import(
    "context"
    "github.com/mengdj/goctl-rest-discover/conf"
    "github.com/mengdj/goctl-rest-discover/factory"
)
type(
    {{range .Type}}
    {{range .Docs -}}{{.}}
    {{- end}}
    {{.RawName}} struct{
    {{if .Members}}
    {{range .Members -}}
        {{if .IsInline}}
            {{.Type.RawName}} //{{if .Docs}} {{range .Docs}}{{.}}{{- end}}{{- end}}
        {{else}}
            {{.Name}} {{.Type.RawName}} {{if .Tag}}{{.Tag}}{{- end}} //{{if .Docs}}{{range .Docs}}{{.}}{{- end}}{{- end}}
        {{- end}}
    {{- end}}
    {{- end}}
    }
    {{- end}}

    // Client
    Client interface{
        {{range .Route -}}
        {{range .Comment -}}
        // {{.}}
        {{- end}}
        // {{.Handler}}
        {{.Handler}}(context.Context,*{{.RequestName}})(*{{.ResponseName}},error)
        {{- end}}
        Invoke(context.Context,string,string,interface{},interface{}) error
    }
    clientFactory struct{
        *factory.RestDiscoverFactory
    }
)

// MustClient
func MustClient(c conf.DiscoverClientConf) Client{
    return &clientFactory{
        RestDiscoverFactory:factory.NewRestDiscoverFactory(c),
    }
}

func (cf *clientFactory) Invoke(ctx context.Context,method string,path string,entity interface{},resp interface{}) error{
    return cf.RestDiscoverFactory.Invoke(ctx,method,path,entity,resp)
}

{{range .Route}}
{{range .Comment}}
// {{.}}
{{- end}}
// {{.Handler}} {{.Text}}
func (cf *clientFactory) {{.Handler}}(ctx context.Context,entity *{{.RequestName}})(resp *{{.ResponseName}},err error){
    resp=new({{.ResponseName}})
    err=cf.Invoke(ctx,"{{.Method}}","{{.Path}}",entity,resp)
    if nil!=err{
        return nil,err
    }
    return resp,nil
}
{{- end}}
